Path manager
UWARG/ZeroPilot-SW pull request #100
Opened 2021-03-25 23:40 UTC by Pop0097

- Crusing state: only thing missing is the part of code that will populate an input struct. Will be added soon 

Please ignore the stupid stuff that I did while updating the branch...

2021-03-29 05:17 UTC, Fberbari requested changes
I'll review this again once you fix things, but I think you guys haven't rebased this stuff onto devel properly, a bunch of files you shouldn't have touched seem to be in this PR.

2021-03-29 05:17 UTC, Fberbari commented on .vscode/c_cpp_properties.json
> +{
This file shouldn't be here

2021-03-29 05:17 UTC, Fberbari commented on Autopilot/CMakeLists.txt
> +  add_subdirectory(DataStructures)
this already exists in devel... no ? Have you rebased on top of devel ?

2021-03-29 05:17 UTC, Fberbari commented on Autopilot/DataStructures/CMakeLists.txt
> +# CMakeLists for DataStructures library
I'm real confused. Why is this part of your commit ? It's already part of devel

2021-03-29 05:17 UTC, Fberbari commented on Autopilot/DataStructures/Inc/vectorClass.hpp
> +/*
same, I think you may have screwed up git

2021-03-30 05:13 UTC, closed without merging

2021-03-30 05:13 UTC, Pop0097 commented
Making a new PR that will be a lot cleaner than this. Sorry for the mess