Implemented the start-up rest causes check
UWARG/ZeroPilot-SW pull request #13
Opened 2018-03-13 01:29 UTC by jamesatuw

Ignore the first two commits and reverts, messed them up. The fifth one is the right one

2018-03-13 15:03 UTC, edenfrosst requested changes
Needs a bit of work. Trying to keep messy files out of the source tree. This file is kind of single-purpose, so it may be worth moving this to a `utilities.c` later, but this will do for now. In the future, please verify that your code compiles before you submit a PR. Makes my life a bit easier.

2018-03-13 15:03 UTC, ianjfrosst commented on Autopilot/Src/reset_cause.c
> +*/
Remove unnecessary commented code

2018-03-13 15:03 UTC, ianjfrosst commented on Autopilot/Src/reset_cause.c
> +    if(_HAL_RCC_GET_FLAG(RCC_FLAG_PINRST)) debug("Pin reset");
None of this code compiles because this macro is typed wrong. Should be `__HAL_RCC_GET_FLAG()` (note the two leading underscores).

2018-03-13 15:03 UTC, ianjfrosst commented on Autopilot/Src/reset_cause.c
> +    else if(_HAL_RCC_GET_FLAG(RCC_FLAG_PORRST)) debug("POR/PWD reset");
Add a check for BORRST (Brown-out reset), too.

2018-03-13 15:03 UTC, ianjfrosst commented on Autopilot/Src/reset_cause.c
> +    else if(_HAL_RCC_GET_FLAG(RCC_FLAG_IWDGRST)) debug("Independent rest");
Debug message here should read "Independent watchdog reset"

2018-03-13 15:03 UTC, ianjfrosst commented on Autopilot/Src/reset_cause.c
> +    else if(_HAL_RCC_GET_FLAG(RCC_FLAG_WWDGRST)) debug("Watch dog reset");
"Window watchdog reset"

2018-03-13 15:03 UTC, ianjfrosst commented on Autopilot/Src/reset_cause.c
> +*/
Commented code shouldn't be merged

2018-03-14 01:02 UTC, ianjfrosst commented on Autopilot/Src/reset_cause.c
> +    if(__HAL_RCC_GET_FLAG(RCC_FLAG_WWDGRST)) debug("Window watch dog reset");
"Watchdog" (one word) and "reset" (spelling) on these two lines.

2018-03-14 01:11 UTC, jamesatuw commented
omg.   Ok.  I will change them.

On Tue, Mar 13, 2018 at 9:02 PM Ian Frosst <notifications@github.com> wrote:

> *@ianjfrosst* commented on this pull request.
> ------------------------------
>
> In Autopilot/Src/reset_cause.c
> <https://github.com/UWARG/ZeroPilot-SW/pull/13#discussion_r174329018>:
>
> > @@ -0,0 +1,12 @@
> +
> +#include "debug.h"
> +#include "stm32f7xx_hal_rcc.h"
> +
> +void reset_cause_check(){
> +    if(__HAL_RCC_GET_FLAG(RCC_FLAG_PINRST)) debug("Pin reset");
> +    if(__HAL_RCC_GET_FLAG(RCC_FLAG_PORRST)) debug("POR/PWD reset");
> +    if(__HAL_RCC_GET_FLAG(RCC_FLAG_SFTRST)) debug("Software reset");
> +    if(__HAL_RCC_GET_FLAG(RCC_FLAG_IWDGRST)) debug("Independent watch dog rest");
> +    if(__HAL_RCC_GET_FLAG(RCC_FLAG_WWDGRST)) debug("Window watch dog reset");
>
> "Watchdog" (one word) and "reset" (spelling) on these two lines.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/UWARG/ZeroPilot-SW/pull/13#pullrequestreview-103664672>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AewX8w7rsZpQqIRnN2ghN5Vi_1d37__Yks5teGw0gaJpZM4Sn8Ua>
> .
>

2018-03-14 14:22 UTC, edenfrosst approved these changes

2018-03-14 14:23 UTC, merged