Enabling all CI tests
UWARG/ZeroPilot-SW pull request #150
Opened 2021-08-08 20:24 UTC by Pop0097

2021-08-12 18:12 UTC, Pop0097 commented
@sahil-kale

2021-08-12 23:39 UTC, sahil-kale requested changes

2021-08-12 23:39 UTC, sahil-kale commented on .travis.yml
> +        - ./Tools/build.bash -c
Do we not launch a testing matrix for Linux systems as well?

2021-08-13 19:16 UTC, sahil-kale approved these changes

2021-08-13 19:17 UTC, merged